### PR TITLE
Mobile View of reactions partly off-screen when translation option is active

### PR DESCRIPTION
**Pull request by odkhang**
Fixes https://github.com/fossasia/eventyay-video/issues/205

## Summary by Sourcery

Fix the issue where the reactions bar is partly off-screen on mobile view when the translation option is active. Enhance the layout and positioning of elements within the ReactionsBar and AudioTranslationDropdown components for better user experience.

Bug Fixes:
- Adjust the positioning of the reactions bar to prevent it from being partly off-screen when the translation option is active on mobile view.

Enhancements:
- Modify the dimensions and positioning of elements within the ReactionsBar component for better alignment and visibility.
- Update the AudioTranslationDropdown component to improve layout and spacing.

### CODE REVIEW

**Comment by odkhang** [comment]
reaction bar not expanded

image

expanded

image

**Comment by mariobehling** [comment]
Please share screenshots

**Comment by mariobehling** [comment]
Currently it is like that and there is a lot of unused white space. Therefore the minimisation/expansion is not really nceessary, is it?

Screenshot from 2024-08-09 01-44-30

Expected would be something like this

355786330-e5ef6efc-2db5-431d-9a1c-ddc25106f1cf

**Comment by odkhang** [comment]
Hi @mariobehling, here the screenshot

image

image

minimisation/expansion is not really nceessary, is it?

-> okay, I will disable expand for reaction bar, make it expanded by default

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
