### PR TITLE
updated the server/requirements.txt to latest version

### PR DESCRIPTION
**Pull request by AviGawande**
Till now there are lot of deprecated version of the server/requirements.txt of eventyay-video and due to this deprecations the cause an error while running the development environment locally. Prior to this PR the dependabot had tried to automate the updations but the changes are not really reflected in the codebase.

### CODE REVIEW

**Comment by hongquan** [comment]
Looks Ok. As far as I remember, there is no breakage when jumping from Django 4.2 to 5.0.

**Comment by marcoag** [comment]
> Looks Ok. As far as I remember, there is no breakage when jumping from Django 4.2 to 5.0.

Really? I'm surprised they bump the major if there's no breaking changes then, but let me check...

**Comment by marcoag** [comment]
Doesn't seem compatible, see "release cadence": https://docs.djangoproject.com/en/dev/internals/release-process/

**Comment by marcoag** [comment]
Have these changes been tested somewhere @AviGawande?

**Comment by AviGawande** [comment]
Not yet , because there was a django-package depreciation in it.

**Comment by marcoag** [comment]
Let's not merge untested dependencies upgrades, that's dangerous, specially with a major update on Django itself.

Let us know when you test it out.

**Review by marcoag — CHANGES_REQUESTED** [review]
Please test, there's too many breaking updates.

**Comment by AviGawande** [comment]
Ok I will test on my branch and let you know

**Review by AviGawande — COMMENTED** [review]
I had successfully tested this the changes in the requirements.txt on my branch of eventyay-tickets.

**Comment by hongquan** [comment]
Please resolve conflict.

**Pull request closed without merging**
