### PR TITLE
Add visual of how many people are watching in each room

### PR DESCRIPTION
**Pull request by lcduong**
> Fixes [#111 Add visual of how many people are watching in each room](https://github.com/fossasia/eventyay-video/issues/111)
> 
> #### Short description of what this resolves:
> Add visual of how many people are watching in each room
> 
> #### Changes proposed in this pull request:
> * Add visual of how many people are watching in each room
> 
> #### Checklist
> * [x]  I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
> * [x]  My branch is up-to-date with the Upstream `development` branch.
> * [ ]  The acceptance, integration, unit tests and linter pass locally with my changes
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks, please add screeshots here.

**Comment by odkhang** [comment]
hi @mariobehling, please find below for a screenshot
image

**Comment by mariobehling** [comment]
Nice! We need to make sure that these numbers also work when people switch across different languages.

**Review by untari — APPROVED** [review]
Screenshot from 2024-07-08 22-56-55

I cherry-pick the changes and test it locally, and the feature works fine it shows how many people watching in real-time

**Review by mariobehling — APPROVED** [review]

**Pull request merged**
