### PR TITLE
Add eventyay video logo

### PR DESCRIPTION
**Pull request by untari**
This PR addresses the logo addition as outlined in [Issue #112](https://github.com/fossasia/eventyay-video/issues/112).

To view the updated logo on the landing page, the database may need to be reset and reloaded. Alternatively, the logo can be updated directly through the webapp by navigating to `Config` -> `Theme`.

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please ensure the logos have the same blue color as on the talk and tickets component. Not purple, should be blue.

**Comment by untari** [comment]
ah okay, as you mentioned in (here https://github.com/fossasia/eventyay-video/issues/112) to use the same colors as on eventyay-video. I thought the logo's supposed to match the background page color.

Will change it to blue color on the logo, shall I change the purple background to match talk and tickets too?

**Comment by mariobehling** [comment]
Sorry. To avoid confusion: Same color and logos on all eventyay components.

**Review by mariobehling — APPROVED** [review]

**Comment by mariobehling** [comment]
@untari Could you please add some screenshots here as well?

**Comment by untari** [comment]
image

**Pull request merged**
